project:
  type: website

website:
  title: Dagmar Heintze
  navbar:
    background: transparent
    foreground: "#ffffff"
    collapse-below: md
    right:
      - href: index.hml
        text: Home
      - text: Research
        menu: 
        - href: research.html
          text: Peer-reviewed Research
        - href: workingpapers.html
          text: Working Papers
      - href: CV_2026.pdf
        text: CV 
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual
